x-sl-defaults: &sl-defaults
  image: simplelogin/$SL_IMAGE:$SL_VERSION
  env_file: .env
  volumes:
    - sldata:/sl
    - upload:/code/static/upload
    ## Uncomment this to use a specific `dkim.key` from the host machine
    #- ./dkim.key:/sl/dkim/dkim.key

services:
  ## SIMPLE LOGIN
  ## ============
  
  postgres:
    image: postgres:12.1
    container_name: sl-db
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - pqdata:/var/lib/postgresql/data
    restart: unless-stopped

  migration:
    <<: *sl-defaults
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -eu
        KEY="$${DKIM_PRIVATE_KEY_PATH:-/sl/dkim/dkim.key}"
        DIR="$$(dirname $$KEY)"
        umask 077
        mkdir -p "$$DIR" "$${GNUPGHOME:-/sl/pgp}"
        if [ ! -s "$$KEY" ]; then
          echo "[dkim-init] No key at $$KEY — generating 1024-bit RSA key..."
          openssl genrsa -out "$$KEY" 1024
        fi
        chmod 600 "$$KEY" 2>/dev/null || true
        exec alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy

  init:
    <<: *sl-defaults
    command: [ "python", "init_app.py" ]
    depends_on:
      migration:
        condition: service_completed_successfully

  app:
    <<: *sl-defaults
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -eu
        KEY="$${DKIM_PRIVATE_KEY_PATH:-/sl/dkim/dkim.key}"
        PUB="$$(openssl rsa -in $$KEY -pubout -outform DER 2>/dev/null | openssl base64 -A)"
        echo "[dkim-init] DKIM public key — add this to your DNS TXT record:"
        echo "v=DKIM1; k=rsa; p=$$PUB"
        exec gunicorn wsgi:app -b 0.0.0.0:7777 -w 2 --timeout 45
    container_name: sl-app
    restart: unless-stopped
    networks:
      - default
      - traefik
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.services.sl-app.loadbalancer.server.port=7777
      - traefik.http.routers.sl-app.rule=Host("${SUBDOMAIN:-app}.${DOMAIN:?DOMAIN_not_set}")
      ## redirect http(s)://$DOMAIN -> https://$SUBDOMAIN.$DOMAIN
      - traefik.http.routers.redir.rule=Host("${DOMAIN}")
      - traefik.http.routers.redir.middlewares=redir,sts
      - traefik.http.middlewares.redir.redirectregex.regex=^https?://${DOMAIN}/?.*
      - traefik.http.middlewares.redir.redirectregex.replacement=https://${SUBDOMAIN:-app}.${DOMAIN}
      ## add STS Header for $DOMAIN and all subdomains
      - traefik.http.middlewares.sts.headers.stsSeconds=31536000
      - traefik.http.middlewares.sts.headers.forceSTSHeader=true 
      - traefik.http.middlewares.sts.headers.stsPreload=true
      - traefik.http.middlewares.sts.headers.stsIncludeSubdomains=true
      ## static response for `mta-sts` subdomain 
      - traefik.http.routers.mta-sts.rule=Host("mta-sts.${DOMAIN}") && PathPrefix("/.well-known/mta-sts.txt")
      - traefik.http.routers.mta-sts.service=noop@internal
      - traefik.http.routers.mta-sts.middlewares=mta-sts
      - traefik.http.middlewares.mta-sts.plugin.staticresponse.StatusCode=200
      - "traefik.http.middlewares.mta-sts.plugin.staticresponse.Body=version: STSv1\nmode: testing\nmx: ${SUBDOMAIN:-app}.${DOMAIN}\nmax_age: 86400"

  email:
    <<: *sl-defaults
    command: ["python", "email_handler.py"]
    container_name: sl-email
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully

  job-runner:
    <<: *sl-defaults
    command: ["python", "job_runner.py"]
    container_name: sl-job-runner
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully

volumes:
  pqdata:
  sldata:
  upload:
